### ISSUE TITLE
`concat_without_safety': can't convert Hash into String (TypeError)

### ISSUE THREAD

**Issue by remyferre** [remyferre/octokit-issues#9]
<a href=https://github.com/jamtur01>  <img src=https://avatars.githubusercontent.com/u/4365?v=3 align=left width=48 height=48 hspace=10></img></a> **Issue by [jamtur01](https://github.com/jamtur01)**
_14/04/2011 at 05:06PM_

 ---- 

I have some code to add a comment to a pull request:

    comment = "blah"
    number = "2"
    @gh_client = Octokit::Client.new(:login => @gh_user, :token => @gh_token)
    @gh_client.add_comment({:username => @gh_org, :repository => repo}, number, comment)

The pull request exists and the auth succeeds but it's returning the following error:

/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/string/output_safety.rb:34:in `concat_without_safety': can't convert Hash into String (TypeError)
	from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/string/output_safety.rb:34:in `<<'
	from /usr/lib/ruby/1.8/openssl/buffering.rb:171:in `do_write'
	from /usr/lib/ruby/1.8/openssl/buffering.rb:193:in `write'
	from /usr/lib/ruby/1.8/net/protocol.rb:177:in `write0'
	from /usr/lib/ruby/1.8/net/protocol.rb:153:in `write'
	from /usr/lib/ruby/1.8/net/protocol.rb:168:in `writing'
	from /usr/lib/ruby/1.8/net/protocol.rb:152:in `write'
	from /usr/lib/ruby/1.8/net/http.rb:1548:in `send_request_with_body'
	from /usr/lib/ruby/1.8/net/http.rb:1533:in `exec'
	from /usr/lib/ruby/1.8/net/http.rb:1049:in `request'
	from /usr/lib/ruby/1.8/net/http.rb:1037:in `request'
	from /usr/lib/ruby/1.8/net/http.rb:543:in `start'
	from /usr/lib/ruby/1.8/net/http.rb:1035:in `request'
	from /usr/lib/ruby/gems/1.8/gems/faraday-0.6.0/lib/faraday/adapter/net_http.rb:50:in `call'
	from /usr/lib/ruby/gems/1.8/gems/faraday-0.6.0/lib/faraday/response.rb:8:in `call'
	from /usr/lib/ruby/gems/1.8/gems/faraday-0.6.0/lib/faraday/request.rb:88:in `run'
	from /usr/lib/ruby/gems/1.8/gems/faraday-0.6.0/lib/faraday/request.rb:28:in `run'
	from /usr/lib/ruby/gems/1.8/gems/faraday-0.6.0/lib/faraday/connection.rb:170:in `run_request'
	from /usr/lib/ruby/gems/1.8/gems/faraday-0.6.0/lib/faraday/connection.rb:69:in `post'
	from /usr/lib/ruby/gems/1.8/gems/octokit-0.6.1/lib/octokit/client/request.rb:23:in `send'
	from /usr/lib/ruby/gems/1.8/gems/octokit-0.6.1/lib/octokit/client/request.rb:23:in `request'
	from /usr/lib/ruby/gems/1.8/gems/octokit-0.6.1/lib/octokit/client/request.rb:9:in `post'
	from /usr/lib/ruby/gems/1.8/gems/octokit-0.6.1/lib/octokit/client/issues.rb:56:in `add_comment'
	from /home/james/src/ghostred/lib/ghostred.rb:101:in `close_pull_request'
	from /home/james/src/ghostred/lib/ghostred.rb:90:in `open_redmine_ticket'
	from /home/james/src/ghostred/lib/ghostred.rb:64:in `get_pull_requests'
	from /home/james/src/ghostred/lib/ghostred.rb:55:in `each'
	from /home/james/src/ghostred/lib/ghostred.rb:55:in `get_pull_requests'
	from /home/james/src/ghostred/lib/ghostred.rb:22:in `run'
	from bin/ghostred:84

Any ideas? I am bit stuck.

Thanks!

**Comment by remyferre** [comment]
<a href=https://github.com/jamtur01>  <img src=https://avatars.githubusercontent.com/u/4365?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [jamtur01](https://github.com/jamtur01)**
_27/04/2011 at 09:03AM_


 ---- 


Hi - any ideas - even if you can point me to - "this is not an octokit problem ... it's one with..."? :)

**Comment by remyferre** [comment]
<a href=https://github.com/pengwynn>  <img src=https://avatars.githubusercontent.com/u/865?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [pengwynn](https://github.com/pengwynn)**
_28/04/2011 at 01:05PM_


 ---- 


From the looks of your stack trace, it appears you're running an older version of Ruby (perhaps the stock Ruby that ships with Mac OSX?) I think we require at least 1.8.7 (1.9.2 is better still), which you can install with [RVM](https://rvm.beginrescueend.com/).

**Comment by remyferre** [comment]
<a href=https://github.com/jamtur01>  <img src=https://avatars.githubusercontent.com/u/4365?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [jamtur01](https://github.com/jamtur01)**
_29/04/2011 at 12:51AM_


 ---- 


Nope:

ruby 1.8.7 (2011-02-18 patchlevel 334) [i386-linux]

**Comment by remyferre** [comment]
<a href=https://github.com/jamtur01>  <img src=https://avatars.githubusercontent.com/u/4365?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [jamtur01](https://github.com/jamtur01)**
_29/04/2011 at 12:52AM_


 ---- 


Blast hit enter too soon.  Ruby is ruby 1.8.7 (2011-02-18 patchlevel 334) [i386-linux] on Fedora 14.

**Comment by remyferre** [comment]
<a href=https://github.com/jamtur01>  <img src=https://avatars.githubusercontent.com/u/4365?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [jamtur01](https://github.com/jamtur01)**
_04/05/2011 at 08:29PM_


 ---- 


I don't get the issue with 1.9.2 albeit I get a new problem:

/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:1735:in `send_request_with_body': undefined method `bytesize' for {:comment=>"comment"}:Hash (NoMethodError)

**Comment by remyferre** [comment]
<a href=https://github.com/catsby>  <img src=https://avatars.githubusercontent.com/u/61721?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [catsby](https://github.com/catsby)**
_17/05/2011 at 01:57AM_


 ---- 


How about if you use `:repo` instead of `:repository` on line 4 of your example?

**Comment by remyferre** [comment]
<a href=https://github.com/jamtur01>  <img src=https://avatars.githubusercontent.com/u/4365?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [jamtur01](https://github.com/jamtur01)**
_17/05/2011 at 05:17AM_


 ---- 


I've tried that a while back - my updated code is:

<pre>
  def self.close_pull_request(number,repo,url)
    @gh_client = Octokit::Client.new(:login => @gh_user, :token => @gh_token)
    puts "Adding comment to GitHub pull request at #{repo}:#{number}"
    comment = "Thanks for your request! It's been moved to our Redmine ticket tracker and you can now track this issue at #{url}"
    @gh_client.add_comment({:username => @gh_org, :repo => repo}, number, comment)
    puts "Closing GitHub issue #{repo}:#{number}"
    @gh_client.close_issue("#{@gh_org}/#{repo}", number)
  end 
</pre>

**Comment by remyferre** [comment]
<a href=https://github.com/catsby>  <img src=https://avatars.githubusercontent.com/u/61721?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [catsby](https://github.com/catsby)**
_17/05/2011 at 12:55PM_


 ---- 


...does it still give you an error?

**Comment by remyferre** [comment]
<a href=https://github.com/jamtur01>  <img src=https://avatars.githubusercontent.com/u/4365?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [jamtur01](https://github.com/jamtur01)**
_18/05/2011 at 05:09AM_


 ---- 


Yes sorry if i wasn't clear. I would have closed the issue if the code had fixed it.

**Comment by remyferre** [comment]
<a href=https://github.com/innonate>  <img src=https://avatars.githubusercontent.com/u/420999?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [innonate](https://github.com/innonate)**
_08/09/2011 at 12:19PM_


 ---- 


Hey gents, this this ever go anywhere? Having a similar error albeit on a different gem. My guess is it lies with Faraday but figured/hoped you found a solution by now that would point me the right way. THanks.

**Comment by remyferre** [comment]
<a href=https://github.com/catsby>  <img src=https://avatars.githubusercontent.com/u/61721?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [catsby](https://github.com/catsby)**
_30/12/2011 at 03:28PM_


 ---- 


What version of Faraday? I still can't reproduce this

    ❯ gem list
    ...
    faraday (0.7.5)
    faraday_middleware (0.7.0)
    ...
    octokit (0.6.5)
    ...

**Comment by remyferre** [comment]
<a href=https://github.com/pengwynn>  <img src=https://avatars.githubusercontent.com/u/865?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [pengwynn](https://github.com/pengwynn)**
_15/04/2012 at 07:28PM_


 ---- 


Closing. Will open back up if we can get some concrete info to reproduce.

**Comment by remyferre** [comment]
<a href=https://github.com/netshade>  <img src=https://avatars.githubusercontent.com/u/3809?v=3 align=left width=48 height=48 hspace=10></img></a> **Comment by [netshade](https://github.com/netshade)**
_24/04/2012 at 05:36PM_


 ---- 


I received a similar issue to this and it seems that I had my Faraday middleware declared in the wrong order.  I had:

      builder.adapter :net_http
      builder.request  :url_encoded

which seemed to cause Faraday to issue the request to `net/http` before it would process my hash params.  Specifying `net_http` as the last middleware in the builder list caused things to work as expected.  While the Octokit lib seems to be doing the right thing here, are you doing anything locally that might cause different elements to be inserted into the Faraday middleware stack?

**Comment by remyferre** [comment]
_The original issue was closed on 15/04/2012 at 07:28PM_
